services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: steam_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: steam_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: steam_zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://steam_kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    container_name: steam_review_producer
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: steam_kafka:9092
      KAFKA_TOPIC: steam_reviews
      DATA_PATH: /app/data/raw/steam_reviews.csv
      MESSAGE_DELAY_SECONDS: 0.0
      MAX_MESSAGES: 5000000
    volumes:
      - ./data:/app/data

  spark:
    build:
      context: .
      dockerfile: spark/Dockerfile
    container_name: steam_spark_streaming
    depends_on:
      - kafka
    volumes:
      - ./data/delta:/app/delta
      - ./data/checkpoints:/app/checkpoints
      - ./reports:/app/reports
      - ./spark/jobs:/app/jobs
      - ./ml:/app/ml
    command: >
      /opt/spark/bin/spark-submit
      --driver-memory 4g
      --conf spark.driver.maxResultSize=2g
      --packages io.delta:delta-spark_2.12:3.2.0,org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1
      /app/jobs/stream_steam_reviews_to_delta.py

  dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    container_name: steam_dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./reports:/app/reports:ro
      - ./data/delta:/app/delta:ro
      - ./ml/models:/app/ml/models:ro
    environment:
      REPORTS_PATH: /app/reports
      DELTA_PATH: /app/delta
      MODELS_PATH: /app/ml/models
    restart: unless-stopped
